module.exports = {
  NOTIFICATION_CHANNEL_NAME: "general",
  
  JOIN_MESSAGES: [
    "🎃 Ô {user} làm gì trong **{channel}** đấyyyyy????!",
    "👀 Nè nè {user}, vào **{channel}** làm gì mà bí ẩn vậy?",
    "✨ Chào mừng {user} đã đột nhập **{channel}** — mission accepted?",
    "🔥 Báo động! {user} xuất hiện tại **{channel}**!",
    "🛸 {user} vừa hạ cánh ở **{channel}**, ai mang bánh kẹo?",
    "🎉 {user} đến rồi — mở confetti cho **{channel}**!",
    "😎 {user} vào **{channel}** — giờ mới có việc để làm!",
    "🍀 Chúc mừng {user} đã tìm thấy **{channel}** — treasure hunt tiếp thôi!",
    "⚡ {user} kích hoạt chế độ support tại **{channel}**!",
    "🤖 Alo {user}, bạn đang ở **{channel}** — thời gian debug bắt đầu!",
    "🐱‍👤 {user} stealth mode off — xuất hiện ở **{channel}**!",
    "🌪️ OMG {user} vừa quét qua **{channel}**, giũa tay đi!",
    "🥳 {user} đã nhảy vào **{channel}** — party time!",
    "🎭 {user} vào **{channel}** với trang phục tuyệt vời (ảo tưởng thôi)!",
    "📣 Attention! {user} joined **{channel}** — xin đặt câu hỏi nào?",
    "🍩 {user} vào **{channel}** — có đem donut không??",
    "🧭 {user} đã lạc vào **{channel}** — có ai hướng dẫn không?",
    "🏄 {user} surf vào **{channel}** — sóng êm hay bão tố?",
    "💡 Ý tưởng mới: {user} vào **{channel}** — note mọi thứ lại!",
    "🎈 {user} ghé thăm **{channel}** — ai đi chơi nàoooo?",
  ],

  LEAVE_MESSAGES: [
    "👋 {user} vừa rời **{channel}** — bay biiii!",
    "🚪 {user} đã thoát khỏi **{channel}** — đi đâu đó à?",
    "😢 Tạm biệt {user} từ **{channel}** — quay lại sớm nhé!",
    "🌙 {user} biến mất khỏi **{channel}** — stealth mode on!",
    "✈️ {user} đã bay khỏi **{channel}** — chuyến bay êm đềm!",
    "🎭 {user} kết thúc phần diễn ở **{channel}** — curtain call!",
    "🏃 {user} chạy khỏi **{channel}** — có gì vội vậy?",
    "💨 Whoosh! {user} đã thoát khỏi **{channel}**!",
    "🌟 {user} rời **{channel}** — mission complete!",
    "🎪 {user} kết thúc show tại **{channel}** — encore?",
    "🚀 {user} blast off từ **{channel}** — đến sao nào đây?",
    "🍃 {user} lướt đi khỏi **{channel}** — nhẹ nhàng quá!",
    "🎬 Cut! {user} rời khỏi **{channel}** — that's a wrap!",
    "🌊 {user} đã offline khỏi **{channel}** — làn sóng lặng!",
    "🎵 {user} tạm biệt **{channel}** — music fades out...",
    "🌈 {user} biến khỏi **{channel}** — tìm cầu vồng khác!",
    "⏰ {user} check-out khỏi **{channel}** — hẹn gặp lại!",
    "🎒 {user} pack đồ rời **{channel}** — adventure tiếp!",
    "💫 {user} tan biến khỏi **{channel}** — magic!",
    "🏖️ {user} nghỉ ngơi rồi rời **{channel}** — relax mode!",
  ],

  ONLINE_MESSAGES: [
    "🟢 {user} vừa online đây — chào buổi sáng/chiều/tối!",
    "✨ {user} đã xuất hiện — ready to roll!",
    "👋 Ê {user} online rồi kìa — ai gọi tui?",
    "🌟 {user} vừa mở mắt — wake up time!",
    "🎮 {user} đã kết nối — game bắt đầu!",
    "💚 {user} status: online — đã sẵn sàng!",
    "🔥 {user} back online — let's do this!",
    "🌈 {user} xuất hiện rồi — hôm nay làm gì nhỉ?",
    "⚡ {user} đã online — powered up!",
    "🎉 {user} joined the party — online rồi nè!",
    "🚀 {user} đã khởi động — to infinity!",
    "🌸 {user} online rồi — hoa nở rồi!",
    "🎪 {user} has entered the server — show time!",
    "💡 {user} đèn sáng rồi — online đây!",
    "🦋 {user} đã bay vào — butterfly effect!",
    "🎯 {user} online — target locked!",
    "🌊 {user} đã lướt vào — wave's here!",
    "🎨 {user} online — canvas ready!",
    "🍕 {user} đã có mặt — pizza time?",
    "🎵 {user} online — music starts!",
  ],

  OFFLINE_MESSAGES: [
    "⚫ {user} vừa offline — ngủ ngon nhé!",
    "💤 {user} đã disconnect — sweet dreams!",
    "🌙 {user} biến mất rồi — see you later!",
    "👻 {user} đã ẩn danh — ghost mode activated!",
    "🔴 {user} offline rồi — tạm biệt!",
    "😴 {user} đã nghỉ — rest time!",
    "🌃 {user} đi ngủ rồi — good night!",
    "✨ {user} tan biến — vanished into the void!",
    "🚪 {user} đóng cửa rồi — see ya!",
    "🌑 {user} chìm vào bóng tối — darkness falls!",
    "💨 Poof! {user} đã bay màu!",
    "📴 {user} tắt nguồn rồi — power down!",
    "🛌 {user} đi nghỉ ngơi — relax mode on!",
    "🎭 {user} hạ màn rồi — curtain closed!",
    "🌠 {user} đã bay xa — shooting star!",
    "⏸️ {user} pause rồi — brb!",
    "🔌 {user} unplugged — disconnected!",
    "🌌 {user} lạc vào vũ trụ — lost in space!",
    "🎬 {user} end scene — that's a wrap!",
    "🌊 {user} chìm xuống đáy — deep dive!",
  ],

  GOOD_MORNING_MESSAGES: [
    "🌅 Chào buổi sáng mọi người! Ngày mới tràn đầy năng lượng nào! ☕✨",
    "☀️ Good morning everyone! Rise and shine — let's make today awesome! 🌟",
    "🌄 Xin chào buổi sáng! Cà phê đã sẵn sàng chưa? ☕😊",
    "🐓 Cock-a-doodle-doo! Ngày mới bắt đầu rồi nè! 🌞",
    "🌻 Chào ngày mới! Hôm nay làm gì vui nhỉ? 🎉",
    "🥐 Good morning! Breakfast time — ai đói bụng chưa? 🍳☕",
    "🌈 Buổi sáng tươi đẹp! Ready to conquer the day? 💪✨",
    "☕ Rise & grind! Cà phê và code thôi nào! 💻🔥",
    "🌞 Wakey wakey! Ngày mới đang chờ đợi! 🎊",
    "🦋 Chào buổi sáng! Hãy làm cho hôm nay thật đặc biệt! 💫",
  ],

  GOOD_NIGHT_MESSAGES: [
    "🌙 Chúc mọi người ngủ ngon! Sweet dreams! 😴✨",
    "⭐ Good night everyone! Nghỉ ngơi thật tốt nhé! 🛌💤",
    "🌃 Đã muộn rồi! Đi ngủ thôi nào — see you tomorrow! 🌠",
    "💫 Chúc ngủ ngon! May your dreams be awesome! 😴🌟",
    "🌜 Night night! Tắt đèn đi ngủ thôi! 🕯️💤",
    "✨ Good night world! Ngày mai gặp lại nha! 🌙😊",
    "🛌 Giờ đi ngủ rồi! Rest well và nạp năng lượng! 💤⚡",
    "🌌 Chúc ngủ ngon! Don't let the bed bugs bite! 🐛😴",
    "💤 Sleepy time! Hẹn gặp lại vào ngày mai! 🌙✨",
    "🌠 Good night! May the stars watch over you! ⭐😴",
  ],

  SCHEDULED_CHANNEL_ID: "1425436238525239317",
};
