module.exports = {
  NOTIFICATION_CHANNEL_NAME: "general",
  
  JOIN_MESSAGES: [
    "🎃 Ô {user} làm gì trong **{channel}** đấyyyyy????!",
    "👀 Nè nè {user}, vào **{channel}** làm gì mà bí ẩn vậy?",
    "✨ Chào mừng {user} đã đột nhập **{channel}** — mission accepted?",
    "🔥 Báo động! {user} xuất hiện tại **{channel}**!",
    "🛸 {user} vừa hạ cánh ở **{channel}**, ai mang bánh kẹo?",
    "🎉 {user} đến rồi — mở confetti cho **{channel}**!",
    "😎 {user} vào **{channel}** — giờ mới có việc để làm!",
    "🍀 Chúc mừng {user} đã tìm thấy **{channel}** — treasure hunt tiếp thôi!",
    "⚡ {user} kích hoạt chế độ support tại **{channel}**!",
    "🤖 Alo {user}, bạn đang ở **{channel}** — thời gian debug bắt đầu!",
    "🐱‍👤 {user} stealth mode off — xuất hiện ở **{channel}**!",
    "🌪️ OMG {user} vừa quét qua **{channel}**, giũa tay đi!",
    "🥳 {user} đã nhảy vào **{channel}** — party time!",
    "🎭 {user} vào **{channel}** với trang phục tuyệt vời (ảo tưởng thôi)!",
    "📣 Attention! {user} joined **{channel}** — xin đặt câu hỏi nào?",
    "🍩 {user} vào **{channel}** — có đem donut không??",
    "🧭 {user} đã lạc vào **{channel}** — có ai hướng dẫn không?",
    "🏄 {user} surf vào **{channel}** — sóng êm hay bão tố?",
    "💡 Ý tưởng mới: {user} vào **{channel}** — note mọi thứ lại!",
    "🎈 {user} ghé thăm **{channel}** — ai đi chơi nàoooo?",
  ],

  LEAVE_MESSAGES: [
    "👋 {user} vừa rời **{channel}** — bay biiii!",
    "🚪 {user} đã thoát khỏi **{channel}** — đi đâu đó à?",
    "😢 Tạm biệt {user} từ **{channel}** — quay lại sớm nhé!",
    "🌙 {user} biến mất khỏi **{channel}** — stealth mode on!",
    "✈️ {user} đã bay khỏi **{channel}** — chuyến bay êm đềm!",
    "🎭 {user} kết thúc phần diễn ở **{channel}** — curtain call!",
    "🏃 {user} chạy khỏi **{channel}** — có gì vội vậy?",
    "💨 Whoosh! {user} đã thoát khỏi **{channel}**!",
    "🌟 {user} rời **{channel}** — mission complete!",
    "🎪 {user} kết thúc show tại **{channel}** — encore?",
    "🚀 {user} blast off từ **{channel}** — đến sao nào đây?",
    "🍃 {user} lướt đi khỏi **{channel}** — nhẹ nhàng quá!",
    "🎬 Cut! {user} rời khỏi **{channel}** — that's a wrap!",
    "🌊 {user} đã offline khỏi **{channel}** — làn sóng lặng!",
    "🎵 {user} tạm biệt **{channel}** — music fades out...",
    "🌈 {user} biến khỏi **{channel}** — tìm cầu vồng khác!",
    "⏰ {user} check-out khỏi **{channel}** — hẹn gặp lại!",
    "🎒 {user} pack đồ rời **{channel}** — adventure tiếp!",
    "💫 {user} tan biến khỏi **{channel}** — magic!",
    "🏖️ {user} nghỉ ngơi rồi rời **{channel}** — relax mode!",
  ],
};
